---
title: "Cronograma das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, cache=FALSE}
source("setup_knitr.R")
```

```{r, eval=FALSE, include=FALSE}
## Gera a lista com as datas de todas as aulas. O resultado do último
## comando pode ser copiado direto para o documento
datas1 <- seq.Date(as.Date("2022-02-01"), as.Date("2022-05-03"), by = "week")
datas1 <- format.Date(datas1, format = "%d/%m")
datas2 <- seq.Date(as.Date("2022-02-03"), as.Date("2022-05-05"), by = "week")
datas2 <- format.Date(datas2, format = "%d/%m")
cat(paste0("- **", datas1, " (Ter)", "**:\n", "- **", datas2, " (Qui)", "**:\n"))
```

- **04/08 (Seg)**: Apresentação da disciplina. Paradigmas para inferência (frequentista, verossimilhança, bayesiano).
  - *Atividade: revisar o Teorema de Bayes como preparação para próxima aula.*
<!--
- **07/08 (Qui)**: Discussão do questionário. Revisões conceituais - Teorema de Bayes.
  - *Atividade 1: fazer cálculos ("na mão" e no R) dos problemas mostrados nos slides. Escrever uma função para calcular o vpp e vpn. Reproduzir cálculos e gráficos mostrados nos slides com sua função.*
  - *Atividade 2: criar uma base de dados que reproduza o exemplo do teste de diagnóstico. A base deve ter 10.000 dados e o resultado de três exames com as mesmas características.*
- **11/08 (Seg)**: extendendo o Teorema de Bayes, informações do teorema baseadas em dados, introdução ao *Naïve* Bayes. 
  - *Atividade 1: Separar o arquivo do conjunto de dados do 3 variáveis classificadores (testes) visto em aula em conjuntos de treino e teste. Usar os resultados do conjunto de treino para prever as observações do conjunto de teste. Veja separação dos conjuntos no (final) do [arquivo de comandos](scripts/aula20250811.R) para todos usarmos a mesma semente de gerador aleatório.*
  - *Atividade 2: analisar com naïve Bayes os dados de Titanic.*
- **14/08 (Qui)** Tópicos adicionais sobre o Naïve Bayes. Classificadoras contínuas. Códigos e pacotes.
  - *Atividade 1: Estudar e rodar códigos do [arquivo de comandos](scripts/aula20250814.R) para classificação com classificadores contínuas.
  - *Atividade 2: Baseando-se nos exemplos anteriores, escrever código de naïve Bayes para um problema com uma classificadora categórica e uma contínua. Use [este arquivo de dados](dados/dadosClass11.csv). Separar conjunto de treino com 75% das observações usando semente seet.seed(2025).*
  - *Atividade 3: Compare resultados de naïve Bayes obtidos até aqui com os obtidos com o uso do pacote "naivebayes".
- **18/08 (Seg)**: Semana Acadêmica.
- **21/08 (Qui)**: Semana Acadêmica.
- **25/08 (Seg)**: Revisitando cálculos do teorema de Bayes em quatro exemplos: teste diagnóstico, questão em exame, problema de Monty Hall, bolas na urna. Gráficos de priori, verossimilhança (padronizada) e posteriori no problema das bolas na urna. Generalizações.
  - *Atividade: Revisitar a solução dos problemas vistos em aula. Revisitar usando formato de solução visto em aula e notação $Y$ e $\theta$ os problemas do Capítulo 1 do material do curso. Implementar computacionalmente os cálculos de todos problemas, incluindo fazer gráficos de prioris, verossimilhanças e posterioris.* 
- **28/08 (Qui)**: Exemplos do Teorema de Bayes. Do discreto para o contínuo: generalizando o exemplo da proporção de canhotos.
- **01/09 (Seg)**: Ainda mais um exemplo de parâmetro discreto. Inferência Bayesiana para a proporção de uma distribuição binomial.
- **04/09 (Qui)**: Do discreto para o contínuo, Modelos Binomial-Beta e Poisson-Gamma. Derivação da obtenção da posteriori.
- **08/09 (Seg)**: Feriado.
- **11/09 (Qui)**: Dedução das expressões da posteriori, marginal (preditiva a priori) e preditiva (a posteriori) para proporção de uma binomial. Ilustrações computacionais: (i) gráficos de priori, verossimilhança e posteriori. Gráficos de preditivas (priori e posteriori). (ii) aproximação por simulação dos resultados analíticos ([arquivo de comandos](scripts/IntroComputation-binom1.R). 
- **15/09 (Seg)**: Dúvidas e resultados para modelo Poisson-Gamma.
- **18/09 (Qui)**: Prova 1.
- **22/09 (Seg)**: Discussão da prova.
- **25/09 (Qui)**: Evento:2SS. Sem aula expositiva. Ver scripts para próxima aula em Materiais.
- **29/09 (Seg)**: Aproximações para posteriori: discretização, aproximação de Laplace (Gaussiana) e reparametrização.
- **02/10 (Qui)**: Revisão aula anterior agora com modelo Poisson. MCMC: programação de caso simples e alguns pacotes para MCMC.
- **06/10 (Seg)**: Resolução em sala de questão semelhante à questão 1 da prova. 
- **09/10 (Qui)**: Princípio da verossimilhança, prioris impróprias, representações de ignorância, priori de Jeffreys, prioris de mistura. 
- **13/10 (Seg)**: Sem aula expositiva. Atividade: ler e preparar capítulo 4 para discussão próxima aula. 
- **16/10 (Qui)**: Transformações/reparametrizações: ilustrações de como prioris em uma escala (parametrização) implicam em prioris equivalentes e outras escalas. Ver script. 
- **20/10 (Seg)**: Obtenção de priori de Jeffreys em alguns casos. Ilustração da invariância sob reparametrização: obtenção por transformação de variáveis e por reparametrização do modelo, ambas levando ao mesmo resultado. Modelos com dois parâmetros: modelo normal com prioris independentes de Jeffreys: obtenção da conjunta, condicionais e marginais. Relações com inferência frequentista.
- **23/10 (Qui)**: Sem aula expositiva
- **27/10 (Seg)**: Modelos com dois parâmetros. Exemplos. 
- **30/10 (Qui)**: Estudos para avaliação. Sem aula expositiva
- **03/11 (Seg)**: Prova 2. 
- **06/11 (Qui)**: Discussão e resolução da Prova 2. 
- **10/11 (Seg)**: Simulações em modelos de dois parâmetros: conjunta, marginais e condicionais. Simulação exata e amostrador de Gibbs. Exemplo da distribuição gama (ver [arquivo de comandos](script/GamaGamaGama.R))
  - *Atividade:* Fazer deduções e simulações análogas para o modelo gaussiano com os dois parâmetros desconhecidos.  
- **13/11 (Qui)**: Introdução a teoria da decisão e resumos da posteriori (Cap 5 até 5.3). 
- **17/11 (Seg)**: Tópicos faltantes do material nos cpts 5, 6 7 e 8. Excluindo Bayes empírico.
- **20/11 (Qui)**: Feriado
- **24/11 (Seg)**: Uso dos JAGS (conteúdo da avaliação, scripts na página, frequencia opcional)
- **27/11 (Qui)**: Sem aula expositiva - tira dúvidas.
- **01/12 (Seg)**: 2a fase vestibular
- **04/12 (Qui)**: Prova 3
- **18/12 (Seg)**: Prova Final

-->


<!--
- **01/02 (Ter)**: Preenchimento e discussão do [questionário preenchido pelos participantes](https://forms.gle/CDnt7X99MYoYsWUh8). Apresentação do curso e da página de disciplina. Introdução às ideias do curso a partir de questões do questionário: teorema de Bayes, inferência frequentista, função de verossimilhança.
  - *Atividades recomendadas:*
    - Associar e interpretar as notações do Teorema de Bayes mostradas na tela durante a aula.
    - Rodar comandos da penúltima questão do questionário e interpretar no contexto de testes de diagnóstico. Qual valor poderia a *sensibilidade do teste*? E a *especificidade*? E a *prevalência*? E o *valor preditivo positivo*? Associar o código ao teorema de Bayes.
    - Rodar comandos da última questão do questionário. Associar a interpretar no contexto de estimação de proporção de canhotos na população mencionado em aula. Como os elementos do gráfico poderiam ser interpretados?
    - Lista de exercícios (1) disponível na sessão de materiais do curso. Sugere-se resolver antes das aulas da próxima semana.
- **03/02 (Qui)**: Visões alternativas do método científico e suas relações com a inferência bayesiana.
  [Slides](slides/metodo-cientifico-inferencia-bayesiana.pdf).
  - *Atividades recomendadas:*
    - Ler o Capítulo 1 da apostila.
    - Tentar resolver a lista de exercícios (1), ou pelo menos pensar a
      respeito das possíveis soluções.
- **08/02 (Ter)**: A aula teve dois temas: i) discussão detalhada do Teorema de Bayes usando o contexto de teste de diagnóstico, explorando formatação, interpretação, jargão do contexto (sensibilidade, espeficidade, prevalência, valor preditivo), possibilidade de testes múltiplos e percepção como um problema de classificação, ii) paradigmas de inferência: usando o problema de estimação de uma proporção foram revisados os paradigmas frequentista e de verossimilhança e feita uma introdução à análise Bayesiana do problema, que será mais explorada na próxima aula [Slides](slides/IntroInferencia.pdf).
  - *Atividades recomendadas:* forma recomendadas ao longo da aula, entre elas:
     - Fazer uma função em R para rápido cálculo do Teorama de Bayes no problema do teste diagnóstico
     - Alterar valores de prevalência, sensibilidade e espeficidade, verificando impacto nos resultados
     - Considerar o uso sequencial de 2 (ou mais!) testes. Usar testes com as mesmas e depois diferentes sensibilidades e especificidades. Para o último caso, verificar se a ordem é importante no resultado final ou se pode haver preferência na recomendação.
     - No problema da estimação da proporção de canhotos: reproduzir análises frequentistas e obtenção da verossimilhança. Expressar sua opinião _a priori_ não apenas com uma valor, mas de forma mais geral com alguma indicação de incerteza.
- **10/02 (Qui)**: Definição de prioris conjugadas e exemplos
  (Beta-Binomial e Poisson-Gamma).
  [Slides](slides/prioris-conjugadas.pdf).
  - *Atividades recomendadas*:
    - Usar a [interface Shiny](http://shiny.leg.ufpr.br/fernandomayer/bayes/) para definir
      diferentes tipos de prioris e ver o impacto na posteriori.
- **15/02 (Ter)**: Discussão de dúvidas e revisão dos principais
  conceitos vistos até agora. Conjugada Beta-Binomial e exemplo dos
  canhotos (ver o [script](scripts/script_canhotos.R)).
- **17/02 (Qui)**: Características do método bayesiano. Testes e princípio da verossimilhança. Atualização sequencial.
- **22/02 (Ter)**: Definição de prioris conjugadas e exemplos: Beta-Binomial (revisão), Poisson-Gama: obtenção da posteriori, esperança da posteriori, obtenção da marginal da resposta Y, esperança e variância.
- **24/02 (Qui)**: Predição Bayesiana. Exemplo no modelo Poisson-Gama. Obtenção da posteriori para média da normal com variância conhecida. Média da posteriori como ponderação da média à priori e estimativa de máxima verossimilhança
  - *Atividades recomendadas*
    - Aplicar os resultados do modelo Poisson Gamma a um conjunto de dados adequado.
    - Obter a posteriori para média da normal com parâmetro de precisão (considerado conhecido).
    - Considere a inferência para o parâmetro de variância (ou de precisão, a sua escolha) da distribuição normal supondo média conhecida. Obter a expressão da posteriori.
- **01/03 (Ter)**: Feriado (carnaval)
- **03/03 (Qui)**: **Aproximação por simulação**. Expressão computacional, por simulação, das distribuições envolvidas no Teoremas de Bayes/Inferência Bayesiana utilizando Modelo Beta-Binomial. Simulação do modelo e obtenção de amostras. Identificação de amostras das distribuições conjunta, marginais e condicionais. Limitações do método para análises de dados. Noção introdutória de algorítmos de aceitação/rejeição.
  - *Atividades recomendadas:*
    - Refazer/reproduzir comandos e simulações mostradas em aula para o modelo beta-binomial.
    - Obter simulações da distribuição preditiva deste mesmo modelo.
    - Fazer análogo para o modelo Poisson gama e para o Modelo Normal-Normal.
    - Seja um modelo com $Y \sim {\rm N}(\theta_i, 1), \theta = (2.5, 3.0, 3.5)$. Adote uma priori uniforme. Considere uma observação $y = 2,8$. Obtenha a posteriori.
    - Idem anterior para observações y = $(2,8; 2,2; 3,1)$.
- **08/03 (Ter)**: **Aproximação por simulação (cont)**. Idem aula anterior. Revisão exemplo com o modelo Poisson-Gamma. Obtenção de preditiva.
  - *Atividades recomendadas*
    - Implementar códigos para os modelos vistos em aula.
    - Rodar exemplos da Binomial-Beta e Poisson Gama com outras escolhas de prioris.
    - Rodar exemplos da Binomial-Beta e Poisson Gama com outros possíveis dados.
    - Implementar versão computacional com aproximação por simulação dos exercícios 2.2 a 2.5.
    - Implementar o algorítmo para comparação de duas proporções.
- **10/03 (Qui)**: Prioris: conceitos fundamentais, prioris na família exponencial, prioris de Jeffrey's
- **15/03 (Ter)**: Prioris: revisão, comentários adicionais sobre prórpias e impróprias. Discussão de exemplo/exercício sugerido. Priori em grid (discretização). Computação de posteriori: Algorítmo MCMC - Metrópolis.
- **17/03 (Qui)**: 1a prova
- **22/03 (Ter)**: Métodos de Monte Carlo. Integração de Monte Carlo e amostragem por importância.
  [HTML](http://cursos.leg.ufpr.br/ce089/06_MC_intro.html).
- **24/03 (Qui)**: Distribuições aproximadas baseadas em simulação de Monte Carlo. Amostragem por rejeição. Re-amostragem por importância.
  [HTML](http://cursos.leg.ufpr.br/ce089/07_MC_aprox.html).
- **29/03 (Ter)**: MCMC: Algoritmos de Metropolis-Hastings. Amostrador independente. Metropolis *random walk*.
  [HTML](http://cursos.leg.ufpr.br/ce089/08_MCMC.html).
- **31/03 (Qui)**: Amostrador de Metropolis-Hastings geral. Amostrador de Gibbs. [HTML](http://cursos.leg.ufpr.br/ce089/08_MCMC.html).
- **05/04 (Ter)**: Teoria da decisão. [PDF](misc/aulas_bayesiana.pdf).
- **07/04 (Qui)**: Teoria da decisão. [PDF](misc/aulas_bayesiana.pdf).
- **12/04 (Ter)**: Testes de hipótese via fator de Bayes.
  [PDF](misc/aulas_bayesiana2.pdf).
- **14/04 (Qui)**: Estimação intervalar. [Script](scripts/exemplo_Bayesiana.R).
- **19/04 (Ter)**:
- **21/04 (Qui)**: Uso de pacotes para inferência bayesiana. [Script 1](scripts/normal.R) e [Script 2](scripts/reglin.R).
- **26/04 (Ter)**: Uso de pacotes para inferência bayesiana. [Script 3](scripts/reglin-random.R).
- **28/04 (Qui)**: Revisão dos capítulos 4, 7 e 8 da apostila.
- **03/05 (Ter)**: Seminários.
- **05/05 (Qui)**: Prova 2.
-->


<!-- - **06/08 (Ter)**: (PJ) Apresentação da disciplina. Trazer a [lista de -->
<!--   exercícios 1](exercicios/ex_intro.pdf) para a próxima aula. -->
<!-- - **08/08 (Qui)**: (PJ) Discussão dos temas apresentados na lista 1. -->
<!-- - **13/08 (Ter)**: (PJ) (dia de paralisação) Aula revisãode conceitos -->
<!-- - **15/08 (Qui)**: (PJ) Comparação entre os paradigmas da inferência -->
<!--   estatística. -->
<!--   - [Slides](oferta201902/CE227-Slides01.pdf) de aula. -->
<!--   - [Script](scripts/script_proporcao.R) feito em sala. -->
<!-- - **20/08 (Ter)**: (PJ) Comparação de duas amostras sob diferentes paradigmas (ver materiais para scripts) -->
<!-- - **22/08 (Qui)**: (PJ) Expecificação de priori e exemplo de Poisson com priori (conjugada) Gama -->
<!-- - **27/08 (Ter)**: (PJ) Discussão e resolução de exercícios do Capítulo 2 -->
<!--   - [Script](oferta201902/codigos/ExerciciosCap2.R) -->
<!-- - **29/08 (Qui)**: (PJ) Avaliação intermediária. -->
<!-- - **03/09 (Ter)**: (PJ) Comentários sobre a avaliação. -->
<!-- - **05/09 (Qui)**: (FM) Definição de prioris e resumo da posteriori. -->
<!--   Slides: [HTML](slides/CE227-Slides02.html). -->
<!--   [PDF](slides/CE227-Slides02.pdf). -->
<!-- - **10/09 (Ter)**: (PJ) Média (esperança) da posteriori como média ponderada entre a amostrar e da priori. Obtenção da posteriori da média da normal (e verificação da relação da esperança). Priori de Jefreys. Exercícios recomendados: Caps 2 e 3 da apostila. -->
<!-- - **12/09 (Qui)**: (PJ) Examinando prioris por simulação e prioris de Jeffreys -->
<!--   - [Script](oferta201902/codigos/priori-simula.R) -->
<!-- - **17/09 (Ter)**: (PJ) -->
<!-- - **19/09 (Qui)**: (PJ) Avaliação intermediária (Cap 3) -->
<!-- - **24/09 (Ter)**: Não haverá aula devido ao SIEPE. -->
<!-- [Resolução 64/18 - CEPE][]. -->
<!-- - **26/09 (Qui)**: Não haverá aula devido ao SIEPE. -->
<!-- [Resolução 64/18 - CEPE][]. -->
<!-- - **01/10 (Ter)**: (PJ) 1a prova -->
<!-- - **03/10 (Qui)**: (PJ) Revisão e discussão da 1a prova -->
<!-- - **08/10 (Ter)**: (PJ) Após obter a posteriori: introdução à decisão, preditiva e aproximação quadrática -->
<!-- - **10/10 (Qui)**: (PJ) Decisão bayesiana. Resumos da posteriori. (Cap 5) -->
<!-- - **15/10 (Ter)**: (PJ) Predição - obtenção da distribuição preditiva (Cap 6) -->
<!-- - **17/10 (Qui)**: (FM) Integração de Monte Carlo: método simples e -->
<!--   amostragem por importância. [HTML](MC_intro.html). -->
<!-- - **22/10 (Ter)**: (PJ) Inferência por simulação. Resumos da posteriori e preditiva. Introdução aos métodos de simulação da posteriori e ao MCMC. -->
<!-- - **24/10 (Qui)**: (FM) Método de aceitação-rejeição. MCMC: -->
<!--   Metropolis-Hastings e Metropolis random walk. [HTML](MCMC-1.html). -->
<!-- - **29/10 (Ter)**: (PJ) Modelos com múltiplos parâmetros. Cap 4 da apostila e exercícios. -->
<!-- - **31/10 (Qui)**: (FM) Método geral de Metropolis-Hastings. -->
<!--   [HTML](MCMC-2.html). Exemplo de amostrador de Gibbs. -->
<!--   [Script](scripts/gibbs_aula1.R). -->
<!-- - **05/11 (Ter)**: (PJ) Algorítmo de Gibbs: dos exemplos, distribuição normal e modelo Poisson com 2 níveis hierárquicos -->
<!--   [Script](scripts/normalGIBBS.R). -->
<!--   [HTML](scripts/PoissonGammaGIBBS.html) -->
<!-- - **07/11 (Qui)**: (FM) Exemplos usando -->
<!--   [JAGS](http://mcmc-jags.sourceforge.net/). -->
<!--   [Script](scripts/gibbs-jags.R). -->
<!-- - **12/11 (Ter)**: Bayes Empírico. Exemplos da apostila e taxas Bayesianas empíricas (Poisson-Gamma) -->
<!-- - **14/11 (Qui)**: (FM) Aplicações via JAGS e INLA: modelos de efeitos -->
<!--   fixos e aleatórios. [Script](scripts/jags-aplicacoes.R). Ver também -->
<!--   exemplo de cáculo do LT-50 em regressão logística, usando inferência -->
<!--   clássica e bayesiana via JAGS e INLA. [HTML](scripts/inf_LT-50.html). -->
<!-- - **19/11 (Ter)**: Preparação das apresentações -->
<!-- - **21/11 (Qui)**: Apresentações do curso -->
<!-- - **26/11 (Ter)**: **Prova 2.** -->
<!-- - **28/11 (Qui)**: CH já integralizada -->
<!-- - **03/12 (Ter)**: CH já integralizada -->
