---
title: "Referências Bibliográficas"
output:
  html_document:
    toc: false
---

## Referências básicas

- Carlin, BP; Louis, TA. **Bayesian methods for data analysis**. Chapman
  & Hall, 2009.
- Coles, S. (tradução e adaptação de Ribeiro Jr, P.J.) [Introdução à Inferência Bayesiana.](http://www.leg.ufpr.br/~paulojus/CE315/InferenciaBayesiana.pdf)
- Gelman, A; Carlin, JB; Stern, HS; Dunson, DB; Vehtari, A; Rubin, DB.
  **Bayesian data analysis**. Chapman & Hall, 2014.
- Hoff, PD. **A first course in Bayesian statistical methods**.  Springer, 2009.
- Kinas, PG; Andrade, HA. **Introdução à análise bayesiana (com R)**. Consultor Editorial, 2020.
- Migon, H, Gamerman, D, & Louzada, F. **Statistical Inference: An Integrated Approach**. Chapman & Hall, 2015.
- Paulino, CD; Turkman, MAA; Murteira, B; Silva, GL. **Estatística bayesiana**. Fundação Calouste Gulbenkian, 2018.
- Stone, JV. **Bayes' Rule: a tutorial introduction to Bayesian
analysis**. Sebtel Press, 2013.

## Referências complementares

- Albert, J. **Bayesian computation with R**. Springer, 2007.
- Gómez-Rubio, V. [Bayesian inference with INLA and R-INLA](https://becarioprecario.bitbucket.io/inla-gitbook/index.html).
- Hobbs, NT; Hooten, MB. **Bayesian models. A ststistical primer for ecologists**. Princeton University Press, 2015.
- Kruschke, JK. **Doing bayesian data analysis**. Academic Press, 2015.
- Lee, PM. **Bayesian ststistics: an introduction**. Arnold, 2004.
- McElreath, R. **Statistical rethinking. A Bayesian course with examples in R and Stan**. Chapman & Hall, 2016.
- Robert, CP; Casella, G. **Introducing Monte Carlo methods in R**. Springer, 2010.
- Sivia, DS; Skilling, J. **Data analysis: a Bayesian tutorial**. Oxford University Press, 2006.

## Leituras complementares

*Leituras relevantes para o tema, mas não necessariamente relacionadas
diretamente com a disciplina.*

- Jaynes, ET. **Probability theory: the logic of science**. Cambridge University Press, 2003.
- Jeffreys, H. **Scientific inference**. Cambridge University Press, 1957.
- Jeffreys, H. [Theory of probability](https://archive.org/details/in.ernet.dli.2015.2608/page/n5).
  Cambridge University Press, 1948.
- Pólya, G. **Mathematics and plausible reasoning**. Princeton University Press, 1990.
